/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import dao.MedicinaDAO;
import dao.VentaDAO;
import model.Venta;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import main.MainFrame;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.time.LocalDate;
import java.util.List;
import model.Medicina;

/**
 *
 * @author Admin
 */
public class AvisoMenu extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    private MainFrame mainFrame;
    private MedicinaDAO medicinaDAO;

    public AvisoMenu(MainFrame mainFrame) {
        this.mainFrame = mainFrame;
        this.medicinaDAO = new MedicinaDAO();
        initComponents();
        cargarAvisos("Medicinas por vencer");
    }

    private void cargarAvisos(String tipoAviso) {
        List<Medicina> medicinas;
        DefaultTableModel model = (DefaultTableModel) tablaAvisos.getModel();
        model.setRowCount(0); // Limpiar tabla

        switch (tipoAviso) {
            case "Medicinas por vencer":
                medicinas = medicinaDAO.obtenerMedicinasPorVencer();
                model.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Fecha de Caducidad"});
                for (Medicina medicina : medicinas) {
                    model.addRow(new Object[]{
                        medicina.getId(),
                        medicina.getNombre(),
                        medicina.getFechaCaducidad()
                    });
                }
                break;
            case "Medicinas con nula existencia":
                medicinas = medicinaDAO.obtenerMedicinasConNulaExistencia();
                model.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Cantidad"});
                for (Medicina medicina : medicinas) {
                    model.addRow(new Object[]{
                        medicina.getId(),
                        medicina.getNombre(),
                        medicina.getCantidad()
                    });
                }
                break;
            case "Medicinas con pocas existencias":
                medicinas = medicinaDAO.obtenerMedicinasConPocasExistencias();
                model.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Cantidad"});
                for (Medicina medicina : medicinas) {
                    model.addRow(new Object[]{
                        medicina.getId(),
                        medicina.getNombre(),
                        medicina.getCantidad()
                    });
                }
                break;
            case "Medicinas con mucha existencia":
                medicinas = medicinaDAO.obtenerMedicinasConMuchaExistencia();
                model.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Cantidad"});
                for (Medicina medicina : medicinas) {
                    model.addRow(new Object[]{
                        medicina.getId(),
                        medicina.getNombre(),
                        medicina.getCantidad()
                    });
                }
                break;
            case "Medicinas con pocas ventas":
                medicinas = medicinaDAO.obtenerMedicinasConPocasVentas();
                model.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Cantidad Vendida"});
                for (Medicina medicina : medicinas) {
                    model.addRow(new Object[]{
                        medicina.getId(),
                        medicina.getNombre(),
                        medicina.getCantidadVendida()
                    });
                }
                break;
            case "Medicinas con muchas ventas":
                medicinas = medicinaDAO.obtenerMedicinasConMuchasVentas();
                model.setColumnIdentifiers(new Object[]{"ID", "Nombre", "Cantidad Vendida"});
                for (Medicina medicina : medicinas) {
                    model.addRow(new Object[]{
                        medicina.getId(),
                        medicina.getNombre(),
                        medicina.getCantidadVendida()
                    });
                }
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bg = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAvisos = new javax.swing.JTable();
        comboAviso = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(780, 446));
        setPreferredSize(new java.awt.Dimension(780, 466));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jLabel2.setText("Avisos");

        btnBuscar.setBackground(new java.awt.Color(25, 118, 210));
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar");

        javax.swing.GroupLayout btnBuscarLayout = new javax.swing.GroupLayout(btnBuscar);
        btnBuscar.setLayout(btnBuscarLayout);
        btnBuscarLayout.setHorizontalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnBuscarLayout.setVerticalGroup(
            btnBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        tablaAvisos.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        tablaAvisos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "ID"
            }
        ));
        jScrollPane1.setViewportView(tablaAvisos);

        comboAviso.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        comboAviso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medicinas por vencer", "Medicinas con nula existencia", "Medicinas con pocas existencias", "Medicinas con mucha existencia", "Medicinas con pocas ventas", "Medicinas con muchas ventas" }));

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(comboAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboAviso))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new Color(73,157,240));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(25,118,210));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        String tipoAviso = (String) comboAviso.getSelectedItem();
        cargarAvisos(tipoAviso);
    }//GEN-LAST:event_btnBuscarMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnBuscar;
    private javax.swing.JComboBox<String> comboAviso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAvisos;
    // End of variables declaration//GEN-END:variables
}
